# In _config.yml
title: My sample book
author: The Jupyter Book Community
logo: icon.png
execute:
  execute_notebooks: force  # or "auto", but "force" ensures widgets are rendered

launch_buttons:
  colab_url: "https://colab.research.google.com"

#parse:
#  myst_enable_extensions:
#    - html_image
#    - dollars_math
#    - linkify
#    - substitution
#    - colon_fence
#    - html_admonition
#    - amsmath
#    - deflist
#    - tasklist
#    - emoji
#    - html_attr


# Add a bibtex file so that we can create citations
# bibtex_bibfiles:



